name: Build/artifacts-only

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install setuptools
        run: pip3 install setuptools --break-system-packages

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: |
            dist/*.exe
            dist/*.zip
          if-no-files-found: error
